[build]
  base = "/"
  command = "echo 'No build command needed'"  # Não precisa de comando de build
  publish = "/"

[functions]
  directory = "/functions"  # Certifique-se de que não há funções para configurar
